name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Cargo commands
      run: |
        cargo fmt --check
        cargo clippy -- -D warnings
        cargo build --release
        cargo test --release
        RUSTDOCFLAGS="-D warnings" cargo doc --release

    - run: |
        echo ${{ github.ref }}

    - if: startsWith( github.ref, 'refs/tags/v' )
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish --package del-geo-core
        cargo publish --package del-geo-nalgebra